#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsseMimmo.Views
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "4.0.3.214")]
public partial class RazorView : RazorViewBase
{

#line hidden

#line 1 "RazorView.cshtml"
public EsseMimmo.Models.Model1 Model { get; set; }

#line default
#line hidden


public override void Execute()
{
WriteLiteral("<html>\r\n<head>\r\n\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"fabric/css/fabric.css\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"fabric/css/fabric.components.css\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"bootstrap/css/bootstrap.css\"");

WriteLiteral(" />\r\n\r\n    <script");

WriteLiteral(" src=\"js/jquery-2.1.4.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"bootstrap/js/bootstrap.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"fabric/js/jquery.fabric.js\"");

WriteLiteral("></script>\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">

        function InvokeCSharpWithFormValues(elm) {

            var elements = document.getElementsByClassName('ms-ListItem is-selected');
            var i = elements.length;
            var menu = """";
            while (i--) {
                menu += elements[i].parentElement.id + "":"" + elements[i].children[1].innerText + "","";
                alert(menu);
            }

            var qs = """";

            var elms = elm.form.elements;

            for (var i = 0; i < elms.length; i++) {
                qs += ""&"" + elms[i].name + ""="" + elms[i].value;
                alert(qs);
            }

            qs += ""&menu="" + menu;

            if (elms.length > 0)
                qs = qs.substring(1);

            location.href = ""hybrid:"" + elm.name + ""?"" + qs;
        }

        function SetLabelText(text) {
            var elm = document.getElementById('label');
            elm.innerHTML = text;
        }

    </script>

    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    $(document).ready(function() {

      if ($('.ms-FilePicker').length > 0) {
        $('.ms-FilePicker').css({
          ""position"": ""absolute !important""
        });

        $('.ms-Panel').FilePicker();
      } else {
        if ($.fn.ListItem) {
          $('.ms-ListItem').ListItem();
        }
      }

      if (typeof fabric !== ""undefined"") {
        if ('ListItem' in fabric) {
          var elements = document.querySelectorAll('.ms-ListItem');
          var i = elements.length;
          var component;
          while(i--) {
            component = new fabric['ListItem'](elements[i]);
          }
        }
      }

    });
    </script>

</head>

<body>
    <div");

WriteLiteral(" data-role=\"page\"");

WriteLiteral(" data-theme=\"b\"");

WriteLiteral(">\r\n        <form>\r\n            <div");

WriteLiteral(" data-role=\"content\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ms-Grid\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"ms-Grid-col ms-u-sm12 ms-u-md12 ms-u-lg12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"ms-Grid-row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"ms-TextField\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" class=\"ms-Label\"");

WriteLiteral(">Nome</label>\r\n                                <input");

WriteLiteral(" class=\"ms-TextField-field\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"nome\"");

WriteLiteral(">\r\n                            </div>\r\n                        </div>\r\n          " +
"              <div");

WriteLiteral(" class=\"ms-Grid-row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"ms-TextField\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" class=\"ms-Label\"");

WriteLiteral(">Email</label>\r\n                                <input");

WriteLiteral(" class=\"ms-TextField-field\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"email\"");

WriteLiteral(">\r\n                            </div>\r\n                        </div>\r\n          " +
"              <div");

WriteLiteral(" class=\"ms-Grid-row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" data-role=\"content\"");

WriteLiteral(" class=\"ms-Grid-col ms-u-sm8 ms-u-md8 ms-u-lg8\"");

WriteLiteral(">\r\n                                <p>Per altri prodotti o quantità sfoglia il <a" +
"");

WriteLiteral(" class=\"ms-Link\"");

WriteLiteral(" href=\"http://www.esselunga.it/statics/volantini/promozioni-1/Zona1-SS-Vol1/index" +
".html\"");

WriteLiteral(">volantino</a>!</p>\r\n                            </div>\r\n                        " +
"    <div");

WriteLiteral(" data-role=\"content\"");

WriteLiteral(" class=\"ms-Grid-col ms-u-sm4 ms-u-md4 ms-u-lg4\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"ms-Button ms-Button--primary\"");

WriteLiteral(" name=\"UpdateLabel\"");

WriteLiteral(" value=\"Ordina!\"");

WriteLiteral(" onclick=\"InvokeCSharpWithFormValues(this)\"");

WriteLiteral(">\r\n                            </div>\r\n                        </div>\r\n          " +
"              <div");

WriteLiteral(" class=\"ms-Grid-row\"");

WriteLiteral(">\r\n                            <ul");

WriteLiteral(" class=\"nav nav-tabs\"");

WriteLiteral(" id=\"menu\"");

WriteLiteral(">\r\n                                <li");

WriteLiteral(" class=\"active\"");

WriteLiteral("><a");

WriteLiteral(" data-target=\"#primi\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral("><span");

WriteLiteral(" class=\"ms-font-m ms-fontColor-themeTertiary\"");

WriteLiteral(">Primi</span></a></li>\r\n                                <li><a");

WriteLiteral(" data-target=\"#secondi\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral("><span");

WriteLiteral(" class=\"ms-font-m ms-fontColor-themeTertiary\"");

WriteLiteral(">Secondi</span></a></li>\r\n                                <li><a");

WriteLiteral(" data-target=\"#insalate\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral("><span");

WriteLiteral(" class=\"ms-font-m ms-fontColor-themeTertiary\"");

WriteLiteral(">Insalate</span></a></li>\r\n                                <li><a");

WriteLiteral(" data-target=\"#frutta\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral("><span");

WriteLiteral(" class=\"ms-font-m ms-fontColor-themeTertiary\"");

WriteLiteral(">Frutta</span></a></li>\r\n                            </ul>\r\n                     " +
"       <div");

WriteLiteral(" class=\"tab-content\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"tab-pane active\"");

WriteLiteral(" id=\"primi\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Lasagne pesto</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n                            " +
"        <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Lasagne magro</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n                            " +
"        <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Paella</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n                            " +
"        <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Trofie pesto</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n                            " +
"        <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Spaghetti riso/pollo-gamberi</span>\r\n                                        <sp" +
"an");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n                            " +
"        <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Spaghetti soia/funghi</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n                            " +
"        <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Pasta Mediterranea</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n                            " +
"        <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Parmigiana Melanzana</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n                            " +
"        <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Pizzoccheri</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n                            " +
"        <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Pasta salmone verdure</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n                            " +
"        <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Cous Cous</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n                            " +
"        <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">30%</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n                            " +
"    </div>\r\n                                <div");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"secondi\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">1/2 Pollo</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n\r\n                          " +
"          <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">1/2 Pollo + patate</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n\r\n                          " +
"          <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Crocchette</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n\r\n                          " +
"          <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Vitello tonnato</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n\r\n                          " +
"          <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Galletto</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n\r\n\r\n                        " +
"            <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Patate</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n\r\n\r\n                        " +
"            <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Salmone</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n\r\n                          " +
"          <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Focaccia</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n\r\n                          " +
"          <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Focaccia farcita</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n\r\n                          " +
"          <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Panino</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n\r\n                          " +
"          <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Cotto</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n\r\n                          " +
"          <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Crudo</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n\r\n                          " +
"          <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Salsiccia</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n\r\n                          " +
"          <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">30%</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n\r\n\r\n                        " +
"        </div>\r\n                                <div");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"insalate\"");

WriteLiteral(">\r\n\r\n                                    <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Insalata di pollo</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n\r\n\r\n                        " +
"            <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Insalata di tacchino</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n\r\n\r\n                        " +
"            <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Insalata di uova/tonno/mozz</span>\r\n                                        <spa" +
"n");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n\r\n                          " +
"          <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Insalata di salmone</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n                            " +
"    </div>\r\n                                <div");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"frutta\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Banana</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n                            " +
"        <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Mela</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n                            " +
"        <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Pesche noci</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n                            " +
"        <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Macedonia</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n                            " +
"        <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Succhi di frutta</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral("></div>\r\n                                    </div>\r\n                            " +
"        <div");

WriteLiteral(" class=\"ms-ListItem is-selectable ms-ListItem--image\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"ms-ListItem-image\"");

WriteLiteral(" style=\"background-color: #767676;\"");

WriteLiteral(">&nbsp;</div>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-primaryText\"");

WriteLiteral(">Mandarini</span>\r\n                                        <span");

WriteLiteral(" class=\"ms-ListItem-secondaryText\"");

WriteLiteral(">Agrumi tipici della Sicilia</span>\r\n                                        <div" +
"");

WriteLiteral(" class=\"ms-ListItem-selectionTarget js-toggleSelection\"");

WriteLiteral(@"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</body>

</html>");

}
}

// NOTE: this is the default generated helper class. You may choose to extract it to a separate file 
// in order to customize it or share it between multiple templates, and specify the template's base 
// class via the @inherits directive.
public abstract class RazorViewBase
{

		// This field is OPTIONAL, but used by the default implementation of Generate, Write, WriteAttribute and WriteLiteral
		//
		System.IO.TextWriter __razor_writer;

		// This method is OPTIONAL
		//
		/// <summary>Executes the template and returns the output as a string.</summary>
		/// <returns>The template output.</returns>
		public string GenerateString ()
		{
			using (var sw = new System.IO.StringWriter ()) {
				Generate (sw);
				return sw.ToString ();
			}
		}

		// This method is OPTIONAL, you may choose to implement Write and WriteLiteral without use of __razor_writer
		// and provide another means of invoking Execute.
		//
		/// <summary>Executes the template, writing to the provided text writer.</summary>
		/// <param name="writer">The TextWriter to which to write the template output.</param>
		public void Generate (System.IO.TextWriter writer)
		{
			__razor_writer = writer;
			Execute ();
			__razor_writer = null;
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the template output without HTML escaping it.</summary>
		/// <param name="value">The literal value.</param>
		protected void WriteLiteral (string value)
		{
			__razor_writer.Write (value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the TextWriter without HTML escaping it.</summary>
		/// <param name="writer">The TextWriter to which to write the literal.</param>
		/// <param name="value">The literal value.</param>
		protected static void WriteLiteralTo (System.IO.TextWriter writer, string value)
		{
			writer.Write (value);
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a value to the template output, HTML escaping it if necessary.</summary>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected void Write (object value)
		{
			WriteTo (__razor_writer, value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes an object value to the TextWriter, HTML escaping it if necessary.</summary>
		/// <param name="writer">The TextWriter to which to write the value.</param>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected static void WriteTo (System.IO.TextWriter writer, object value)
		{
			if (value == null)
				return;

			var write = value as Action<System.IO.TextWriter>;
			if (write != null) {
				write (writer);
				return;
			}

			//NOTE: a more sophisticated implementation would write safe and pre-escaped values directly to the
			//instead of double-escaping. See System.Web.IHtmlString in ASP.NET 4.0 for an example of this.
			writer.Write(System.Net.WebUtility.HtmlEncode (value.ToString ()));
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to the template output.
		/// </summary>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		protected void WriteAttribute (string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			WriteAttributeTo (__razor_writer, name, prefix, suffix, values);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to a TextWriter.
		/// </summary>
		/// <param name="writer">The TextWriter to which to write the attribute.</param>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		///<remarks>Used by Razor helpers to write attributes.</remarks>
		protected static void WriteAttributeTo (System.IO.TextWriter writer, string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			// this is based on System.Web.WebPages.WebPageExecutingBase
			// Copyright (c) Microsoft Open Technologies, Inc.
			// Licensed under the Apache License, Version 2.0
			if (values.Length == 0) {
				// Explicitly empty attribute, so write the prefix and suffix
				writer.Write (prefix);
				writer.Write (suffix);
				return;
			}

			bool first = true;
			bool wroteSomething = false;

			for (int i = 0; i < values.Length; i++) {
				Tuple<string,object,bool> attrVal = values [i];
				string attPrefix = attrVal.Item1;
				object value = attrVal.Item2;
				bool isLiteral = attrVal.Item3;

				if (value == null) {
					// Nothing to write
					continue;
				}

				// The special cases here are that the value we're writing might already be a string, or that the
				// value might be a bool. If the value is the bool 'true' we want to write the attribute name instead
				// of the string 'true'. If the value is the bool 'false' we don't want to write anything.
				//
				// Otherwise the value is another object (perhaps an IHtmlString), and we'll ask it to format itself.
				string stringValue;
				bool? boolValue = value as bool?;
				if (boolValue == true) {
					stringValue = name;
				} else if (boolValue == false) {
					continue;
				} else {
					stringValue = value as string;
				}

				if (first) {
					writer.Write (prefix);
					first = false;
				} else {
					writer.Write (attPrefix);
				}

				if (isLiteral) {
					writer.Write (stringValue ?? value);
				} else {
					WriteTo (writer, stringValue ?? value);
				}
				wroteSomething = true;
			}
			if (wroteSomething) {
				writer.Write (suffix);
			}
		}
		// This method is REQUIRED. The generated Razor subclass will override it with the generated code.
		//
		///<summary>Executes the template, writing output to the Write and WriteLiteral methods.</summary>.
		///<remarks>Not intended to be called directly. Call the Generate method instead.</remarks>
		public abstract void Execute ();

}
}
#pragma warning restore 1591
